export const locators = {
  login: {
    email: "[data-qa='login-email']",
    password: "[data-qa='login-password']",
    loginButton: "[data-qa='login-button']",
  },
  signUpLoginButton: "#header ul > li:nth-child(4) > a",
  newUserSignupHeader: "#form div:nth-child(3) h2",
  signupName: "[data-qa='signup-name']",
  signupEmail: "[data-qa='signup-email']",
  signupButton: "[data-qa='signup-button']",

  registerForm: {
    registerName: "[data-qa='name']",
    registerEmail: "[data-qa='email']",
    registerPassword: "[data-qa='password']",
    registerDay: "[data-qa='days']",
    registerMonth: "[data-qa='months']",
    registerYear: "[data-qa='years']",
    registerNewsletter: "#newsletter",
    registerSpecialOffers: "#optin",
    addressFirstName: "[data-qa='first_name']",
    addressLastName: "[data-qa='last_name']",
    addressCompany: "[data-qa='company']",
    addressAddress: "[data-qa='address']",
    addressCountry: "[data-qa='country']",
    addressState: "[data-qa='state']",
    addressCity: "[data-qa='city']",
    addressZipCode: "[data-qa='zipcode']",
    addressMobilePhone: "[data-qa='mobile_number']",
    addressCreateAccountButton: "[data-qa='create-account']",
  },
  continueButton: "[data-qa='continue-button']",
  deleteAccountButton: "#header li:nth-child(5) > a",

  homepage: {
    subscribeEmail: "#susbscribe_email",
    subscribeButton: "#subscribe",
    header: "#header",
    slider: "#slider",
    sliderCarousel: "#slider-carousel",
    accordian: "#accordian",
    cartModal: "#cartModal",
    viewCartLink: "#cartModal a[href='/view_cart']",
    continueShoppingButton: "#cartModal .close-modal",
    recommendedItemCarousel: "#recommended-item-carousel",
    footer: "#footer",
    successSubscribe: "#success-subscribe",
    scrollUp: "#scrollUp",
    signUpLoginButton: "a[href='/login']",
    productsButton: "a[href='/products']",
    featuredItemsTitle: ".features_items .title.text-center",
    productCards: ".features_items .product-image-wrapper",
  },
  products: {
    allProductsTitle: ".features_items .title.text-center",
    productCards: ".features_items .product-image-wrapper",
    productName: ".productinfo p",
    productPrice: ".productinfo h2",
    searchProduct: "#search_product",
    searchInput: "#search_product",
    submitSearch: "#submit_search",
    searchButton: "#submit_search",
    saleImage: "#sale_image",
    accordian: "#accordian",
    categoryWomen: "#Women",
    categoryMen: "#Men",
    categoryKids: "#Kids",
    addToCartButton: "[data-product-id]",
    overlayAddToCartButton: ".product-overlay .add-to-cart",
    viewProductLink: "a[href*='/product_details/']",
    addedToCartModal: "#cartModal",
    viewCartLink: "#cartModal a[href='/view_cart']",
    continueShoppingButton: "#cartModal .close-modal",
  },
  cartPage: {
    advertisement: "#card",
    closeAdvertisement: "dismiss-button-element",
    cartItemsSection: "#cart_items",
    breadcrumbs: ".breadcrumb",
    cartInfo: "#cart_info",
    cartInfoTable: "#cart_info_table",
    emptyCart: "#empty_cart",
    productRow: "[id^='product-']",
    productDescription: ".cart_description",
    productPrice: ".cart_price",
    productQuantity: ".cart_quantity",
    productTotal: ".cart_total",
    deleteProductButton: ".cart_quantity_delete",
    proceedToCheckoutButton: ".check_out",
    checkoutModal: "#checkoutModal",
    registerLoginLink: "#checkoutModal a[href='/login']",
    closeCheckoutModal: ".close-checkout-modal",
    continueOnCartLink: "#empty_cart a[href='/products']",
  },
  signupPage: {
    signupHeader: ".signup-form h2",
    signupName: "[data-qa='signup-name']",
    signupEmail: "[data-qa='signup-email']",
    signupButton: "[data-qa='signup-button']",
    registerName: "[data-qa='name']",
    registerEmail: "[data-qa='email']",
    registerPassword: "[data-qa='password']",
    registerDay: "[data-qa='days']",
    registerMonth: "[data-qa='months']",
    registerYear: "[data-qa='years']",
    registerNewsletter: "#newsletter",
    registerSpecialOffers: "#optin",
    addressFirstName: "[data-qa='first_name']",
    addressLastName: "[data-qa='last_name']",
    addressCompany: "[data-qa='company']",
    addressAddress: "[data-qa='address']",
    addressCountry: "[data-qa='country']",
    addressState: "[data-qa='state']",
    addressCity: "[data-qa='city']",
    addressZipCode: "[data-qa='zipcode']",
    addressMobilePhone: "[data-qa='mobile_number']",
    createAccountButton: "[data-qa='create-account']",
    accountCreatedTitle: "[data-qa='account-created']",
    continueButton: "[data-qa='continue-button']",
    deleteAccountButton: "a[href='/delete_account']",
  },
};
